#!/bin/bash
#SBATCH --job-name=myjob         # Job name
#SBATCH --nodes=1                # Request 1 node (OpenMP runs on one machine)
#SBATCH --ntasks=1               # Run 1 task (your program)
#SBATCH --cpus-per-task=32       # Request 32 CPUs for that 1 task
#SBATCH --output=output.log      # Output file
#SBATCH --error=error.log        # Error log file

#Compile, if not already done
make

#Run 5 times for each thread count - static scheduling
for dynamic in 0 1
do
    for thread_count in 1 4 8 16 32
    do
        for i in {1..5}
        do
            ./kmeans_parallel $thread_count $dynamic
        done
    done
done